// Sync the Qirtas reading app (PWA + Capacitor) with the platform catalog.
// Metadata → js/books.js (light, lazy text loading) ; texts → ./books/<id>.json
// Usage: node tools/sync-catalog.js
'use strict';
const fs = require('fs');
const path = require('path');

const APP = path.join(__dirname, '..');
const PLATFORM = path.join(APP, '..', 'qirtas');
const CATALOG = path.join(PLATFORM, 'books-data', 'catalog.json');
const TEXTS = path.join(PLATFORM, 'books-data', 'texts');
const OUT_BOOKS = path.join(APP, 'js', 'books.js');
const OUT_TEXT_DIR = path.join(APP, 'books');

if (!fs.existsSync(CATALOG)) {
  console.error('catalog not found: ' + CATALOG);
  process.exit(1);
}

const catalog = JSON.parse(fs.readFileSync(CATALOG, 'utf8'));
fs.mkdirSync(OUT_TEXT_DIR, { recursive: true });

const CATEGORIES = [
  { id: 'all', ar: 'الكل', en: 'All' },
  { id: 'arabic', ar: 'كلاسيكيات عربية', en: 'Arabic Classics' },
  { id: 'english', ar: 'كلاسيكيات إنجليزية', en: 'English Classics' },
];

// Order: Arabic first (app default language), then English; newest first inside each.
const sorted = [...catalog].sort((a, b) => {
  if (a.lang !== b.lang) return a.lang === 'ar' ? -1 : 1;
  return String(b.addedAt || '').localeCompare(String(a.addedAt || ''));
});

let copied = 0, missing = 0;
const books = sorted.map((b) => {
  const src = path.join(TEXTS, b.id + '.json');
  let chapterCount = b.chapters || 0;
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(OUT_TEXT_DIR, b.id + '.json'));
    copied++;
  } else { missing++; }

  return {
    id: b.id,
    grad: b.grad || 'cover-g3',
    emoji: b.emoji || '📚',
    cat: b.cat || 'english',
    lang: b.lang || 'en',
    title: { ar: (b.title && (b.title.ar || b.title.en)) || b.id, en: (b.title && (b.title.en || b.title.ar)) || b.id },
    author: { ar: (b.author && (b.author.ar || b.author.en)) || '', en: (b.author && (b.author.en || b.author.ar)) || '' },
    year: b.year || '',
    description: {
      ar: (b.description && (b.description.ar || b.description.en)) || '',
      en: (b.description && (b.description.en || b.description.ar)) || '',
    },
    chapterCount,
    words: b.words || 0,
    source: (b.sourceLabel && b.sourceLabel.ar) || b.source || '',
    sourceUrl: b.sourceUrl || '',
    license: (b.licenseLabel && b.licenseLabel.ar) || 'ملكية عامة',
    chapters: [], // loaded lazily from ./books/<id>.json
  };
});

const header = `/* Qirtas app library — generated by tools/sync-catalog.js.
   Do not edit by hand. Source of truth: ../qirtas/books-data/catalog.json
   Book texts are loaded lazily from ./books/<id>.json (offline-cached by sw.js). */

const CATEGORIES = ${JSON.stringify(CATEGORIES, null, 2)};

const BOOKS = ` + JSON.stringify(books, null, 2) + ';\n';

fs.writeFileSync(OUT_BOOKS, header);

const kb = (fs.statSync(OUT_BOOKS).size / 1024).toFixed(0);
console.log(`sync-catalog: ${books.length} books → js/books.js (${kb} KB), ${copied} texts copied, ${missing} missing`);
const byLang = {};
for (const b of books) byLang[b.lang] = (byLang[b.lang] || 0) + 1;
console.log('by lang: ' + JSON.stringify(byLang));
